### ISSUE TITLE
Broken Build - AllDistrctGen.java and StarGenerator.java

### ISSUE THREAD

**Issue by jody** [MetroCS/redistricting#49]
**Describe the bug**
```
% ant compile
Buildfile: redistricting/build.xml

init:

compile:
    [javac] Compiling 19 source files to redistricting/build/classes
    [javac] redistricting/src/swdmt/redistricting/AllDistrictGen.java:128: error: <identifier> expected
    [javac]   private AllDistrictGen {
    [javac]                         ^
    [javac] redistricting/src/swdmt/redistricting/StarGenerator.java:79: error: <identifier> expected
    [javac]   private StarGenerator {
    [javac]                        ^
    [javac] 2 errors

BUILD FAILED
redistricting/build.xml:126: Compile failed; see the compiler error output for details.

Total time: 0 seconds
```

**To Reproduce**
1. Issue build command `ant compile`
2. See error

**Expected behavior**
No compilation errors.

**Desktop (please complete the following information):**
 - OS: OSX 10.14.3
 - Version: JDK 9, JDK 12

**Additional context**
Code was _not adequately tested_ before pull requests and _not adequately reviewed_ before merged.

Appears to be error in failing to put required `()` in constructor signatures.

**Comment by jody** [comment]
Reverted the offending pull requests.
Associated user stories also need to be reopened.
